{
    "title": "python-requests-Kerberos through 0.5 does not handle mutual authentication",
    "score": 9.8,
    "severity": "CRITICAL",
    "cwe_id": "CWE-287",
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "cpe_match": [
        "cpe:2.3:a:requests-kerberos_project:requests-kerberos:*:*:*:*:*:*:*:*",
        "cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "techniqueId": "T1059",
            "confidence": "93.6",
            "techniqueName": "Command and Scripting Interpreter"
        }
    ]
}
