{
    "title": "A use-after-free flaw was found in the io_uring in Linux kernel, where a local attacker with a user privilege could cause a denial of service problem on the system The issue results from the lack of validating the existence of an object prior to performing operations on the object by not incrementing the file reference counter while in use. The highest threat from this vulnerability is to data integrity, confidentiality and system availability.",
    "score": 7.8,
    "severity": "HIGH",
    "cwe_id": "CWE-416",
    "cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    "cpe_match": [
        "cpe:2.3:o:linux:linux_kernel:-:*:*:*:*:*:*:*",
        "cpe:2.3:a:netapp:cloud_backup:-:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": []
}
