{
    "title": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.1 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, a different vulnerability than CVE-2010-3494.",
    "score": 4.3,
    "severity": "MEDIUM",
    "cwe_id": "CWE-362",
    "cvss_vector": "CVSS:2.0/AV:N/AC:M/Au:N/C:N/I:N/A:P",
    "cpe_match": [
        "cpe:2.3:a:g.rodola:pyftpdlib:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.4.0:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.2.0:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.1.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.3.0:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": []
}
