{
    "title": "The ftp_QUIT function in ftpserver.py in pyftpdlib before 0.5.0 allows remote authenticated users to cause a denial of service (file descriptor exhaustion and daemon outage) by sending a QUIT command during a disallowed data-transfer attempt.",
    "score": 4.0,
    "severity": "MEDIUM",
    "cwe_id": "CWE-20",
    "cvss_vector": "CVSS:2.0/AV:N/AC:L/Au:S/C:N/I:N/A:P",
    "cpe_match": [
        "cpe:2.3:a:g.rodola:pyftpdlib:0.2.0:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.1.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.3.0:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "techniqueId": "T1489",
            "techniqueName": "Service Stop",
            "confidence": "3.0"
        },
        {
            "techniqueId": "T1498",
            "techniqueName": "Network Denial of Service",
            "confidence": "37.8"
        },
        {
            "techniqueId": "T1499",
            "techniqueName": "Endpoint Denial of Service",
            "confidence": "40.3"
        }
    ]
}
