{
    "title": "TensorFlow is an end-to-end open source platform for machine learning. In affected versions an attacker can trigger a crash via a floating point exception in `tf.raw_ops.ResourceGather`. The [implementation](https://github.com/tensorflow/tensorflow/blob/f24faa153ad31a4b51578f8181d3aaab77a1ddeb/tensorflow/core/kernels/resource_variable_ops.cc#L725-L731) computes the value of a value, `batch_size`, and then divides by it without checking that this value is not 0. We have patched the issue in GitHub commit ac117ee8a8ea57b73d34665cdf00ef3303bc0b11. The fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.",
    "score": 5.5,
    "severity": "MEDIUM",
    "cwe_id": "CWE-369",
    "cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "cpe_match": [
        "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:google:tensorflow:2.6.0:rc2:*:*:*:*:*:*",
        "cpe:2.3:a:google:tensorflow:2.6.0:rc1:*:*:*:*:*:*",
        "cpe:2.3:a:google:tensorflow:2.6.0:rc0:*:*:*:*:*:*",
        "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:google:tensorflow:2.5.0:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "technique_id": "T1083",
            "confidence": "27.0",
            "technique_name": "File and Directory Discovery"
        },
        {
            "technique_id": "T1102",
            "confidence": "10.6",
            "technique_name": "Web Service"
        },
        {
            "technique_id": "T1219",
            "confidence": "10.9",
            "technique_name": "Remote Access Software"
        }
    ]
}
