{
    "title": "In teler before version 0.0.1, if you run teler inside a Docker container and encounter `errors.Exit` function, it will cause denial-of-service (`SIGSEGV`) because it doesnt get process ID and process group ID of teler properly to kills. The issue is patched in teler 0.0.1 and 0.0.1-dev5.1.",
    "score": 7.5,
    "severity": "HIGH",
    "cwe_id": "CWE-476",
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "cpe_match": [
        "cpe:2.3:a:teler_project:teler:*:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "techniqueId": "T1033",
            "confidence": "3.7",
            "techniqueName": "System Owner/User Discovery"
        },
        {
            "techniqueId": "T1055",
            "confidence": "23.0",
            "techniqueName": "Process Injection"
        },
        {
            "techniqueId": "T1057",
            "confidence": "33.4",
            "techniqueName": "Process Discovery"
        },
        {
            "techniqueId": "T1505.003",
            "confidence": "3.6",
            "techniqueName": "Web Shell"
        },
        {
            "techniqueId": "T1518.001",
            "confidence": "5.7",
            "techniqueName": "Security Software Discovery"
        },
        {
            "techniqueId": "T1533",
            "confidence": "5.8",
            "techniqueName": "Data from Local System"
        },
        {
            "techniqueId": "T1057",
            "confidence": "2.1",
            "techniqueName": "Process Discovery"
        },
        {
            "techniqueId": "T1087",
            "confidence": "2.8",
            "techniqueName": "Account Discovery"
        },
        {
            "techniqueId": "T1213",
            "confidence": "2.1",
            "techniqueName": "Data from Information Repositories"
        }
    ]
}
