{
    "title": "TensorFlow is an end-to-end open source platform for machine learning. An attacker can cause a denial of service by exploiting a `CHECK`-failure coming from `tf.raw_ops.LoadAndRemapMatrix`. This is because the implementation(https://github.com/tensorflow/tensorflow/blob/d94227d43aa125ad8b54115c03cece54f6a1977b/tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc#L219-L222) assumes that the `ckpt_path` is always a valid scalar. However, an attacker can send any other tensor as the first argument of `LoadAndRemapMatrix`. This would cause the rank `CHECK` in `scalar<T>()()` to trigger and terminate the process. The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.",
    "score": 5.5,
    "severity": "MEDIUM",
    "cwe_id": "CWE-617",
    "cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "cpe_match": [
        "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "technique_id": "T1083",
            "confidence": "27.0",
            "technique_name": "File and Directory Discovery"
        },
        {
            "technique_id": "T1102",
            "confidence": "21.5",
            "technique_name": "Web Service"
        },
        {
            "technique_id": "T1557.001",
            "confidence": "10.3",
            "technique_name": "LLMNR/NBT-NS Poisoning and SMB Relay"
        },
        {
            "technique_id": "T1057",
            "confidence": "38.9",
            "technique_name": "Process Discovery"
        },
        {
            "technique_id": "T1219",
            "confidence": "10.9",
            "technique_name": "Remote Access Software"
        }
    ]
}
