{
    "title": "The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack.",
    "score": 8.1,
    "severity": "HIGH",
    "cwe_id": "CWE-287",
    "cvss_vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "cpe_match": [
        "cpe:2.3:a:apple:pykerberos:-:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "techniqueId": "T1489",
            "techniqueName": "Service Stop",
            "confidence": "5.6"
        },
        {
            "techniqueId": "T1498",
            "techniqueName": "Network Denial of Service",
            "confidence": "37.0"
        },
        {
            "techniqueId": "T1499",
            "techniqueName": "Endpoint Denial of Service",
            "confidence": "42.1"
        }
    ]
}
